alt-1 = ['workspace 1-web', 'workspace 1-dev']
alt-2 = ['workspace 2-web', 'workspace 2-dev']
alt-3 = ['workspace 3-web', 'workspace 3-dev']
alt-4 = ['workspace 4-web', 'workspace 4-dev']
alt-5 = ['workspace 5-web', 'workspace 5-dev']
